language: generic
sudo: required
services:
  - docker

env:
  global:
    - DOCKER_IMAGE=rss-bridge
    - LATEST=2018-08-07
    - VERSION_KEEP_PATCH=true
  matrix:
    - VERSION=2018-08-07
    - VERSION=2018-06-10
    - VERSION=master

before_install:
  - ./ci/install-docker.sh

install: true

before_script:
  - docker --version
  - docker info

script:
  - docker build --build-arg=RSS_BRIDGE_VERSION=${VERSION} -t ${DOCKER_USERNAME}/${DOCKER_IMAGE}:${VERSION} ./
  - docker-compose -f ./ci/docker-compose.yml -d
  - curl "http://localhost/?action=display&bridge=Twitter&u=sadserver&format=Atom" | grep "<feed"

before_deploy:
  - ./ci/docker-login.sh

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master

